### PR TITLE
Add support for TypedArray

### LINKED ISSUE #19: Support for ArrayBuffers
Is it possible to support `ArrayBuffer` and similar structures like `Uint8Array`, `Float32Array`, etc?

Ideally it would be great if I can pass a `Uint8Array` as argument and it will give me the same type array back.

Right now I'd have to convert the ArrayBuffer to the DataPoint structure and that's very inefficient in my case.

### PR DESCRIPTION
**Pull request by janjakubnanista**
This PR adds support for `TypedArray` input format ([see more on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays)).

Downsampling functions are now symmetrical in regards to the input - if `Float64Array` is passed in, `Float64Array` will be returned.

Resolves #19

### CODE REVIEW

**Comment by janjakubnanista** [comment]
Hey @Christilut! I opened a new PR to address your issue with typed arrays. Could you have a look if this fixes your problems?

**Comment by Christilut** [comment]
Thanks! I tried it but my webpack doesn't seem to like it. It keeps saying it can't find the module after installing it with NPM, directly from github: `npm i janjakubnanista/downsample#pull/21/head`
Looks like installing it like that has many files missing, I don't see any source files then.

Tried it as local files too but had other errors.

**Comment by janjakubnanista** [comment]
@Christilut ah yes you will need to build the package if you are installing from a branch/commit. I think it's easier if I send you 
[a build artefact instead](https://github.com/janjakubnanista/downsample/files/5995523/downsample.zip). Just unzip it into your `node_modules/downsample` and you should be good to go.

**Comment by Christilut** [comment]
Thanks, I'm getting further with it. But looks like the typings aren't updated for TypedArrays yet?

```ts
    const channelData = buffer.getChannelData(0)

    audioData.waveformDataLow = LTTB(channelData, audioData.audioBuffer.duration * 600)
```

Errors:
```
src/classes/AudioAnalyzer/process.ts:93:5 - error TS2322: Type 'Indexable<DataPoint>' is not assignable to type 'ArrayBufferLike'.
  Type 'Indexable<DataPoint>' is missing the following properties from type 'SharedArrayBuffer': byteLength, slice, [Symbol.species], [Symbol.toStringTag]

93     audioData.waveformDataLow = LTTB(channelData, audioData.audioBuffer.duration * 600)
       ~~~~~~~~~~~~~~~~~~~~~~~~~

src/classes/AudioAnalyzer/process.ts:93:38 - error TS2345: Argument of type 'Float32Array' is not assignable to parameter of type 'Indexable<DataPoint>'.
  Index signatures are incompatible.
    Type 'number' is not assignable to type 'DataPoint'.

93     audioData.waveformDataLow = LTTB(channelData, audioData.audioBuffer.duration * 600)
```

**Comment by janjakubnanista** [comment]
Let me add your code to the test suites, I will push a change once the errors are gone!

**Comment by janjakubnanista** [comment]
I finally had time to look into this and I realised I overlooked one very obvious thing :)

What is most probably happening is you are probably importing `LTTB` from `downsample`:

```typescript
import { LTTB } from 'downsample';
```

This is sort of a reasonable default - it accepts input as an array of `DataPoint`s. What you need instead is something like this:

```typescript
import { createLTTB } from `downsample`;

const LTTB = createLTTB({
  x: (point: number, index: number) => index,
  y: (point: number) => point,
});
```

This way you create a `LTTB` function that accepts an array of numbers. After that the type errors should disappear!

Let me know if that worked for you!

**Comment by Christilut** [comment]
Thanks, that works great! I'm going to test it more in the next few days.
You should add that last code snippet to the `TypedArray support` portion of the documentation.

**Comment by Christilut** [comment]
How do you instantiate the createASAP function? I'm not sure what the `toPoint` does.

**Comment by janjakubnanista** [comment]
So the `LTD`, `LTTB` and `LTOB` downsample the data by picking the best data points from the original array. `ASAP` and `SMA` on the other hand create new data points so they need a way to take an X and Y value and convert those into a data point, that is what `toPoint` does.

I am going to add this to the docs!

**Comment by janjakubnanista** [comment]
I am going to merge this PR, I have more related things coming that I want in `1.4.0` still so test the new code and if you still have any issues please report them or reopen issue #19

**Comment by Christilut** [comment]
Awesome! I'll experiment with it further soon.

**Pull request merged**
